// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using SDWebImage;
using Shared;
using UIKit;

namespace LFSDemo
{
	public partial class FeedItemCell : UITableViewCell
	{
		public FeedItemCell (IntPtr handle) : base (handle)
		{
		}

        public void LoadData(FeedItem item)
        {
            NameLabel.Text = item.Author.FirstName + " " + item.Author.LastName;
            MessageLabel.Text = item.Message;
            //ProfileImageView.Image = UIImage.LoadFromData(NSData.FromArray(item.Author.ProfilePicture));
            ProfileImageView.SetImage(NSUrl.FromString(item.Author.ProfilePictureUrl));

            if (item.ImageUrl != null || item.Image != null)
            {
                ImageView.SetImage(NSUrl.FromString(item.ImageUrl));
                //ImageView.Image = UIImage.LoadFromData(NSData.FromArray(item.Image));
                Constraint_ImageViewRatio.Constant = 0;
            }
            else
            {
                ImageView.Image = null;
                Constraint_ImageViewRatio.Constant = ImageView.Frame.Width;
            }

            this.NeedsUpdateConstraints();
            this.SetNeedsLayout();
        }
	}
}
